#!/bin/bash
[ ! -f /usr/bin/ffmpeg ] && echo && echo ""$0" depends on ffmpeg" && echo && exit

[ $# -ne 1 ] && echo && echo "Syntax: "$0" inputformat outputformat" && echo && exit
for a in ./*.$1; do
  ffmpeg -i "$a" -qscale:a 0 "${a[@]/%$1/$2}"
done

