#!/bin/bash
mountable=$(lsblk -rp | grep part | grep -v SWAP | grep -v sda | grep -v "t /" | awk '{print $1, "(" $4 ")"}')
[[ "$mountable" = "" ]] && exit 1

chosen=$(echo "$mountable" | dmenu -i -p "Mount which drive?" | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1
name=$(echo "" | dmenu -i -p "Name to mount")

pmount $chosen $name && pgrep -x dunst && notify-send "$chosen mounted to /media/$name."
