#!/bin/bash

[[ $BLOCK_BUTTON = "1" ]] && st -e ranger

homefree=$(df -h | awk '$6=="/home"{print $4}')
mounted=$(df -h | awk '$1~/\/dev/&&$1!~/sda/{printf "%s (%s) ",$6,$4}')

echo ["$homefree"] "$mounted"
