#!/bin/bash

[[ $BLOCK_BUTTON = "1" ]] && \
	notify-send "RAM\n\n$(ps axch -o cmd:15,%mem --sort=-%mem | sed 11q)"
mem=$(free -h | awk '$1~/Mem/{print $3}')
swap=$(free -h | awk '$1~/Swap/{print $3}')

echo "$mem" / "$swap"
